context_aspect_ratio: 1
context_scale: !!python/tuple
- 0.85
- 1.0
decoder_depth: 6
img_size: 224
lr: 0.001
m: 0.996
m_start_end: !!python/tuple
- 0.996
- 1.0
num_target_blocks: 4
patch_size: 224
target_aspect_ratio: !!python/tuple
- 0.75
- 1.5
target_scale_interval: !!python/tuple
- 0.15
- 0.2
vit: !!python/name:model.vit.vit_nano ''
weight_decay: 0.05
